automi:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  automi_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - head_pan
      - head_tilt
      - r_shoulder_r
      - r_shoulder_p
      - r_elbow
      - l_shoulder_r
      - l_shoulder_p
      - l_elbow
      - r_hip_y
      - r_hip_r
      - r_hip_p
      - r_knee
      - r_ankle_r
      - r_ankle_p
      - l_hip_y
      - l_hip_r
      - l_hip_p
      - l_knee
      - l_ankle_r
      - l_ankle_p
    
    gains:
      head_pan:
        p: 100.0
        i: 0.01
        d: 10.0
    
      head_tilt:
        p: 100.0
        d: 0.01
        d: 10.0
    
      r_shoulder_r:
        p: 100.0
        i: 0.01
        d: 10.01
    
      r_shoulder_p:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_elbow:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_shoulder_r:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_shoulder_p:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_elbow:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_hip_y:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_hip_r:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_hip_p:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_knee:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_ankle_r:
        p: 100.0
        i: 0.01
        d: 10.0
    
      r_ankle_p:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_hip_y:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_hip_r:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_hip_p:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_knee:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_ankle_r:
        p: 100.0
        i: 0.01
        d: 10.0
    
      l_ankle_p:
        p: 100.0
        i: 0.01
        d: 10.0
    
    joint_trajectory_action_node:
      joints:
        - head_pan
        - head_tilt
        - r_shoulder_r
        - r_shoulder_p
        - r_elbow
        - l_shoulder_r
        - l_shoulder_p
        - l_elbow
        - r_hip_y
        - r_hip_r
        - r_hip_p
        - r_knee
        - r_ankle_r
        - r_ankle_p
        - l_hip_y
        - l_hip_r
        - l_hip_p
        - l_knee
        - l_ankle_r
        - l_ankle_p
      constraints:
        goal_time: 1.0
        head_pan:
          goal: 0.0
        head_tilt:
          goal: 0.0
        r_shoulder_r:
          goal: 0.0
        r_shoulder_p:
          goal: 0.0
        r_elbow:
          goal: 0.0
        l_shoulder_r:
          goal: 0.0
        l_shoulder_p:
          goal: 0.0
        l_elbow:
          goal: 0.0
        r_hip_y:
          goal: 0.0
        r_hip_r:
          goal: 0.0
        r_hip_p:
          goal: 0.0
        r_knee:
          goal: 0.0
        r_ankle_r:
          goal: 0.0
        r_ankle_p:
          goal: 0.0
        l_hip_y:
          goal: 0.0
        l_hip_r:
          goal: 0.0
        l_hip_p:
          goal: 0.0
        l_knee:
          goal: 0.0
        l_ankle_r:
          goal: 0.0
        l_ankle_p:
          goal: 0.0
  
  # # HEAD
  # head_pan_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: head_pan
  #   pid: {p: 100.0, d: 10.01, d: 10.0}

  # head_tilt_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: head_tilt
  #   pid: {p: 100.0, d: 10.01, d: 10.0}


  # # ARMS

  # r_shoulder_r_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_shoulder_r
  #   pid: {p: 100.0, d: 10.01, d: 10.0}

  # r_shoulder_p_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_shoulder_p
  #   pid: {p: 100.0, d: 10.01, d: 10.0}

  # r_elbow_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_elbow
  #   pid: {p: 100.0, d: 10.01, d: 10.0}

  # l_shoulder_r_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_shoulder_r
  #   pid: {p: 100.0, d: 10.01, d: 10.0}

  # l_shoulder_p_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_shoulder_p
  #   pid: {p: 100.0, d: 10.01, d: 10.0}

  # l_elbow_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_elbow
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # # LEGS

  # r_hip_y_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_hip_y
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # r_hip_r_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_hip_r
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # r_hip_p_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_hip_p
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # r_knee_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_knee
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # r_ankle_r_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_ankle_r
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # r_ankle_p_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: r_ankle_p
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # l_hip_y_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_hip_y
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # l_hip_r_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_hip_r
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # l_hip_p_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_hip_p
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # l_knee_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_knee
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # l_ankle_r_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_ankle_r
  #   pid: {p: 100.0, d: 10.01, d: 10.0}



  # l_ankle_p_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: l_ankle_p
  #   pid: {p: 100.0, d: 10.01, d: 10.0}
